---
apiVersion: v1
kind: Service
metadata:
  name: konnectivity-server
  labels:
    app: kube-apiserver
spec:
  type: NodePort
  selector:
    app: kube-apiserver
  ports:
    - port: {{ .KonnectivityAgentPort }}
      targetPort: {{ .KonnectivityAgentPort }}
{{- if .KonnectivityServerAgentNodePort }}
      nodePort: {{ .KonnectivityServerAgentNodePort }}
{{- end }}
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: konnectivity-server-local
  labels:
    app: kube-apiserver
spec:
  type: ClusterIP
  selector:
    app: kube-apiserver
  ports:
    - port: {{ .KonnectivityServerPort }}
      targetPort: {{ .KonnectivityServerPort }}
      protocol: TCP
