---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: konnectivity-agent
  namespace: kube-system
  labels:
    app: konnectivity-agent
    kubernetes-dashboard-policy: allow
    dashboard-metrics-scraper-policy: allow
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      app: konnectivity-agent
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: konnectivity-agent
        kubernetes-dashboard-policy: allow
        dashboard-metrics-scraper-policy: allow
    spec:
      automountServiceAccountToken: false
      priorityClassName: system-node-critical
      containers:
      - name: konnectivity-agent
        image: {{ imageFor "apiserver-network-proxy" }}
        imagePullPolicy: IfNotPresent
{{- if .KonnectivitySecurityContext }}
{{- $securityContext := .KonnectivitySecurityContext }}
        securityContext:
          runAsUser: {{ $securityContext.RunAsUser }}
{{- end }}
        command: ["/bin/proxy-agent"]
        args: [
          "--logtostderr=true",
          "--ca-cert=/etc/konnectivity/ca/ca.crt",
          "--proxy-server-host={{ .KonnectivityServerURL }}",
          "--proxy-server-port={{ .KonnectivityServerAgentNodePort }}",
          "--health-server-port={{ .KonnectivityAgentHealthPort }}",
          "--agent-cert=/etc/konnectivity/agent/tls.crt",
          "--agent-key=/etc/konnectivity/agent/tls.key",
          "--agent-identifiers=ipv4=$(HOST_IP)&default-route=true",
          "--keepalive-time=30s",
          "--probe-interval=30s",
          "--sync-interval=1m",
          "--sync-interval-cap=5m",
          "--v=3"
          ]
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .KonnectivityAgentHealthPort }}
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 60
          failureThreshold: 3
          timeoutSeconds: 30
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
{{- if .KonnectivityAgentContainerResources }}
        resources: {{ range .KonnectivityAgentContainerResources }}{{ range .ResourceRequest }}
          requests: {{ if .CPU }}
            cpu: {{ .CPU }}{{ end }}{{ if .Memory }}
            memory: {{ .Memory }}{{ end }}{{ end }}{{ end }}
{{- end }}
        volumeMounts:
        - mountPath: /etc/konnectivity/ca
          name: konnectivity-ca
        - mountPath: /etc/konnectivity/agent
          name: agent-certs
      tolerations:
      - operator: "Exists"
      volumes:
      - name: agent-certs
        secret:
          secretName: konnectivity-agent
          defaultMode: 0640
      - name: konnectivity-ca
        configMap:
          defaultMode: 0640
          name: konnectivity-ca-bundle
