---
apiVersion: v1
kind: Service
metadata:
  name: konnectivity-server
spec:
  type: NodePort
  selector:
    app: kube-apiserver
  ports:
    - port: {{ .KonnectivityAgentClusterPort }}
      targetPort: {{ .KonnectivityAgentClusterPort }}
{{- if .KonnectivityServerNodePort }}
      nodePort: {{ .KonnectivityServerNodePort }}
{{- end }}
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: konnectivity-server-local
spec:
  type: ClusterIP
  selector:
    app: kube-apiserver
  ports:
    - port: {{ .KonnectivityServerClusterPort }}
      targetPort: {{ .KonnectivityServerClusterPort }}
      protocol: TCP
