kind: Deployment
apiVersion: apps/v1
metadata:
  name: openshift-apiserver
spec:
  replicas: {{ .Replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: openshift-apiserver
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: openshift-apiserver
        clusterID: "{{ .ClusterID }}"
{{ if .RestartDate }}
      annotations:
        openshift.io/restartedAt: "{{ .RestartDate }}"
{{ end }}
    spec:
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "master-{{ .ClusterID }}"
          effect: NoSchedule
        - key: "multi-az-worker"
          operator: "Equal"
          value: "true"
          effect: NoSchedule
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: dedicated
                operator: In
                values:
                - master-{{ .ClusterID }}
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: clusterID
                      operator: In
                      values: ["{{ .ClusterID }}"]
                topologyKey: "kubernetes.io/hostname"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values: ["openshift-apiserver"]
              topologyKey: "kubernetes.io/hostname"
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values: ["openshift-apiserver"]
              topologyKey: "topology.kubernetes.io/zone"
      automountServiceAccountToken: false
{{ if .MasterPriorityClass }}
      priorityClassName: {{ .MasterPriorityClass }}
{{ end }}
      terminationGracePeriodSeconds: 90
      containers:
{{- if .KonnectivityEnabled }}
      - name: socks5-proxy
{{- if .OpenshiftAPIServerSecurityContext }}
{{- $securityContext := .OpenshiftAPIServerSecurityContext }}
        securityContext:
          runAsUser: {{ $securityContext.RunAsUser }}
{{- end }}
        image: {{ imageFor "hypershift" }}
        imagePullPolicy: IfNotPresent
        args:
        - run
        command:
        - /usr/bin/control-plane-operator
        - konnectivity-socks5-proxy
        env:
        - name: KUBECONFIG
          value: /etc/kubernetes/secrets/kubeconfig/kubeconfig
{{- if .Socks5ProxyContainerResources }}
        resources: {{ range .Socks5ProxyContainerResources }}{{ range .ResourceRequest }}
          requests: {{ if .CPU }}
            cpu: {{ .CPU }}{{ end }}{{ if .Memory }}
            memory: {{ .Memory }}{{ end }}{{ end }}{{ range .ResourceLimit }}
          limits: {{ if .CPU }}
            cpu: {{ .CPU }}{{ end }}{{ if .Memory }}
            memory: {{ .Memory }}{{ end }}{{ end }}{{ end }}
{{- end }}
        lifecycle:
          preStop:
            exec:
              command:
                - /bin/sh
                - -c
                - sleep 70
        volumeMounts:
        - mountPath: /etc/kubernetes/secrets/kubeconfig
          name: kubeconfig
        - mountPath: /etc/konnectivity/proxy-ca
          name: oas-konnectivity-proxy-ca
        - mountPath: /etc/konnectivity/proxy-client
          name: oas-konnectivity-proxy-cert
{{- end }}
      - name: openshift-apiserver
{{- if .OpenshiftAPIServerSecurityContext }}
{{- $securityContext := .OpenshiftAPIServerSecurityContext }}
        securityContext:
          runAsUser: {{ $securityContext.RunAsUser }}
{{- end }}
        image: {{ imageFor "openshift-apiserver" }}
        args:
        - "start"
        - "--config=/etc/kubernetes/apiserver-config/config.yaml"
        - "--authorization-kubeconfig=/etc/kubernetes/secret/kubeconfig"
        - "--authentication-kubeconfig=/etc/kubernetes/secret/kubeconfig"
        - "--requestheader-client-ca-file=/etc/kubernetes/config/aggregator-client-ca.crt"
        - "--requestheader-allowed-names=kube-apiserver-proxy,system:kube-apiserver-proxy,system:openshift-aggregator"
        - "--requestheader-username-headers=X-Remote-User"
        - "--requestheader-group-headers=X-Remote-Group"
        - "--requestheader-extra-headers-prefix=X-Remote-Extra-"
        - "--client-ca-file=/etc/kubernetes/config/serving-ca.crt"
        livenessProbe:
          httpGet:
            scheme: HTTPS
            port: 8443
            path: livez
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            scheme: HTTPS
            port: 8443
            path: readyz
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
          successThreshold: 1
{{ if .OpenshiftAPIServerResources }}
        resources:{{ range .OpenshiftAPIServerResources }}{{ range .ResourceRequest }}
          requests: {{ if .CPU }}
            cpu: {{ .CPU }}{{ end }}{{ if .Memory }}
            memory: {{ .Memory }}{{ end }}{{ end }}{{ range .ResourceLimit }}
          limits: {{ if .CPU }}
            cpu: {{ .CPU }}{{ end }}{{ if .Memory }}
            memory: {{ .Memory }}{{ end }}{{ end }}{{ end }}
{{ end }}
{{- if .KonnectivityEnabled }}
        env:
        - name: "HTTP_PROXY"
          value: "socks5://127.0.0.1:{{ .KonnectivityServerClusterPort }}"
        - name: "HTTPS_PROXY"
          value: "socks5://127.0.0.1:{{ .KonnectivityServerClusterPort }}"
        - name: "NO_PROXY"
          value: "{{ .OpenshiftAPIServerNoProxyHosts }}"
{{- end }}
        volumeMounts:
        - mountPath: /etc/kubernetes/secret
          name: secret
        - mountPath: /etc/kubernetes/apiserver-config
          name: apiserver-config
        - mountPath: /etc/kubernetes/config
          name: config
        - mountPath: /var/run/kubernetes
          name: logs
        workingDir: /var/run/kubernetes
      volumes:
      - secret:
          secretName: openshift-apiserver
          defaultMode: 0640
        name: secret
      - configMap:
          name: openshift-apiserver
        name: config
      - configMap:
          name: openshift-apiserver-config
        name: apiserver-config
      - emptyDir: {}
        name: logs
{{- if .KonnectivityEnabled }}
      - secret:
          secretName: service-network-admin-kubeconfig
          defaultMode: 0640
        name: kubeconfig
      - name: oas-konnectivity-proxy-cert
        secret:
          defaultMode: 0640
          secretName: konnectivity-client
      - configMap:
          defaultMode: 0640
          name: konnectivity-ca-bundle
        name: oas-konnectivity-proxy-ca
{{- end }}
